config/routes.rb
Chess::Application.routes.draw do
  
  devise_for :players
  resource :dashboard, :only => [:show]
  resources :games, :only => [:new, :create, :show, :index, :update]
  resources :pieces, :only => [:create, :show, :update]
    

  root 'static_pages#index'

  
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chess</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- TOP NAV BAR -->
 <div id="wrap">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Pawnage', root_path, :class => 'navbar-brand' %>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
			      <%-# need to add player_signed_in? method to player model (MH 6-18-15) #-%>            
            <%-# if player_signed_in? #-%>
              <li><%=link_to 'Sign in', new_player_session_path %></li>
              <li><%=link_to 'Sign out', destroy_player_session_path, :method => :delete %></li>
              <li><%=link_to 'Sign up', new_player_registration_path %></li>
              <li class="divider"></li>  
              <li><%=link_to 'My Dashboard', dashboard_path %></li>
            <%-# end #-%>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%-# Devise flash alerts to notify user of successful or unsuccessful sign-in #-%>
<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%=alert %></p>
<% end %>
<%-# end #-%>
	
<%= yield %>
 
</body>
</html>